name: workflow-ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLflow Project (Retrain)
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:mlruns
      run: |
        mlflow run . | tee output.log

    - name: Debug mlruns structure
      working-directory: MLProject
      run: |
        tree mlruns -L 3 || find mlruns -maxdepth 3 -type d

    - name: Get latest RUN_ID
      working-directory: MLProject
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs basename)
    
        if [ -z "$RUN_ID" ]; then
          echo "ERROR: RUN_ID not found"
          exit 1
        fi
    
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Detected RUN_ID=$RUN_ID"

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image from MLflow Model
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:mlruns
      run: |
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n mlflow-model

    - name: Tag & Push Docker Image
      run: |
        docker tag mlflow-model:latest \
          ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest

        
