name: MLflow CI Retraining - Advanced

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Run MLflow Project (Training)
        shell: bash -l {0}
        run: |
          cd MLProject
          export MLFLOW_TRACKING_URI=file:${GITHUB_WORKSPACE}/MLProject/mlruns
          mlflow run . --env-manager=local | tee output.log

      - name: Get latest RUN_ID
        shell: bash -l {0}
        run: |
          cd MLProject
          RUN_ID=$(ls -td mlruns/*/* | head -1 | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "MODEL_PATH=runs:/$RUN_ID/model" >> $GITHUB_ENV
          echo "Detected RUN_ID=$RUN_ID"

      - name: Upload MLflow Artifacts (Skilled)
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns

      - name: Build Docker Image from MLflow Model
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n abalone-mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image (Advanced)
        run: |
          docker tag abalone-mlflow:latest \
            ${{ secrets.DOCKER_USERNAME }}/abalone-mlflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/abalone-mlflow:latest
