name: MLflow CI Retraining

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Run MLflow Project (Training)
        shell: bash -l {0}
        run: |
          cd MLProject
          export MLFLOW_TRACKING_URI=file:${GITHUB_WORKSPACE}/MLProject/mlruns
          mlflow run . --env-manager=local

      - name: Get RUN_ID
        run: |
          # Robustly grab the RUN_ID from the file created by Python
          RUN_ID=$(cat MLProject/run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "MODEL_PATH=runs:/$RUN_ID/model" >> $GITHUB_ENV
          echo "Proceeding with Run ID: $RUN_ID"

      - name: Upload MLflow Artifacts (Skilled)
              uses: actions/upload-artifact@v4
              with:
                name: mlflow-artifacts
                path: MLProject/mlruns
                retention-days: 5

      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          cd MLProject
          # Building even if accuracy was low
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n abalone-mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag abalone-mlflow:latest ${{ secrets.DOCKER_USERNAME }}/abalone-mlflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/abalone-mlflow:latest
