name: workflow-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install MLflow
      run: pip install mlflow

    - name: Debug working directory
      working-directory: MLProject
      run: |
        pwd
        ls -R

    - name: Run MLflow Project
      working-directory: MLProject
      run: mlflow run . --env-manager=local

    - name: Check MLruns folder
      working-directory: MLProject
      run: |
        echo "Contents of MLProject/mlruns:"
        ls -R mlruns || echo "mlruns folder not found"
      
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    - name: List mlruns folder
      working-directory: MLProject
      run: ls -R mlruns

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | \
        docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

