name: workflow-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install mlflow scikit-learn pandas

    - name: Run MLflow training
      working-directory: MLProject
      run: |
        RUN_ID=$(python modelling.py | grep MLFLOW_RUN_ID | cut -d= -f2)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image from MLflow model
      run: |
        cd MLProject
        MODEL_PATH="mlruns/0/$RUN_ID/artifacts/model"
        ls -la "$MODEL_PATH"
        mlflow models build-docker -m "$MODEL_PATH" -n bbc-mlflow

    - name: Tag Docker Image
      run: |
        docker tag bbc-mlflow:latest ${{ secrets.DOCKER_USERNAME }}/bbc-mlflow:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/bbc-mlflow:latest
