name: workflow-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install mlflow scikit-learn pandas

    - name: Run MLflow training
      working-directory: MLProject
      run: |
        OUTPUT=$(python modelling.py)
        echo "$OUTPUT"
    
        RUN_ID=$(echo "$OUTPUT" | grep MLFLOW_RUN_ID | cut -d= -f2)
        ARTIFACT_URI=$(echo "$OUTPUT" | grep MLFLOW_ARTIFACT_URI | cut -d= -f2)
    
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "ARTIFACT_URI=$ARTIFACT_URI" >> $GITHUB_ENV

    - name: Debug artifacts
      run: |
        cd MLProject
        find mlruns -maxdepth 5 -type d

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image from MLflow model
      run: |
        cd MLProject
        echo "Building from run_id=$RUN_ID"
        mlflow models build-docker -m "runs:/$RUN_ID/model" -n mlflow-model

    - name: Tag Docker Image
      run: |
        docker tag mlflow-model:latest ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
