name: workflow-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install mlflow scikit-learn pandas

    - name: Run MLflow training
      working-directory: MLProject
      run: |
        python modelling.py
    
    - name: Get latest MLflow run
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:mlruns
      run: |
        mlflow runs list --experiment-name "Eksperimen Latih Model Dataset Abalone"
    
        RUN_ID=$(mlflow runs list \
          --experiment-name "Eksperimen Latih Model Dataset Abalone" \
          --order-by start_time DESC \
          --max-results 1 \
          | tail -n 1 | awk '{print $1}')
    
        if [ -z "$RUN_ID" ]; then
          echo "ERROR: RUN_ID is empty"
          exit 1
        fi
    
        ARTIFACT_URI=$(mlflow runs describe -r $RUN_ID \
          | grep Artifact | awk '{print $3}')
    
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "ARTIFACT_URI=$ARTIFACT_URI" >> $GITHUB_ENV

    - name: Debug artifacts
      run: |
        cd MLProject
        find mlruns -maxdepth 5 -type d

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image from MLflow model
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:mlruns
      run: |
        echo "Using RUN_ID=$RUN_ID"
        mlflow models build-docker -m "runs:/$RUN_ID/model" -n mlflow-model

    - name: Tag Docker Image
      run: |
        docker tag mlflow-model:latest ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
